FROM node:12.16.1-alpine As builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install \
    && npm run postbuild

COPY . .

RUN npx tsc

FROM nginx:1.15.8-alpine

COPY --from=builder /usr/src/app/site/ /usr/share/nginx/html